import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";
import Footer from "./Component/Footer";


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Daraz Clone",
  description: "Generated by create next app",
    icons: {
    icon: 'https://img.lazcdn.com/us/domino/da7668ef-2724-447a-951a-558dafdfb265_NP-60-60.png', // /public path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body> 
        
        <Header/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
